# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate species concentrations
#'
#' @param CConc vector of
CppCalcSpecConc <- function(CConc, K, Stoich, NComp, NSpec) {
    .Call(`_BLMEngineInR_CppCalcSpecConc`, CConc, K, Stoich, NComp, NSpec)
}

