# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title CHemical Equilibria in Soils and Solutions
#'
#' @description Given a chemical system, equilibria equations, and total
#'   concentrations of components, calculate the species concentrations of each
#'   chemical product in the system.
#'
#' @param QuietFlag character, one of "Very Quiet" (only print out when run is
#'   done), "Quiet" (print out Obs=iObs), or "Debug" (print out lots of info)
#' @param ConvergenceCriteria numeric, the maximum value of MaxError that 
#'   counts as convergence by the Newton-Raphson root-finding algorithm
#' @param MaxIter integer, the maximum number of iterations the Newton-Raphson
#'   root-finding algorithm should do before giving up
#' @param NComp integer, number of components
#' @param NSpec integer, number of species reactions
#' @param NBLMetal integer, the number of biotic ligand-bound metal species 
#'   that are associated with toxic effects.
#' @param SpecK numeric vector (NSpec), the equilibrium coefficient of the
#'   formation reactions
#' @param SpecStoich signed integer matrix (NSpec x NComp), the reaction
#'   stoichiometry of the formation reactions
#' @param SpecCtoM numeric vector (NSpec), the concentration to mass conversion
#'   factor of the chemical species for which we have formation reactions
#' @param SpecName character vector (NSpec), the name of the chemical species
#'   for which we have formation reactions
#' @param CompType character vector (NComp), the type of each component in the
#'   simulation
#' @param CompName character vector (NComp), the name of each component in the
#'   simulation
#' @param TotMoles numeric vector (NComp), the total moles of each component in
#'   the simulation (units of mol)
#' @param TotConc numeric vector (NComp), the total concentrations of each
#'   component in the simulation (units of e.g., mol/L and mol/kg)
#' @param DoTox logical, TRUE for toxicity mode where the MetalName component
#'   concentration is adjusted to try to match the CATarget with BLMetalSpecs
#' @param MetalName character string, the name of the toxic metal
#' @param MetalComp integer, the position of the metal in the component arrays
#'   (i.e., which is the toxic metal component) Note: this are base-1 indexed.
#' @param BLMetalSpecs integer vector, the positions of the species in the
#'   arrays which contribute to toxicity (i.e., which species are the toxic
#'   metal bound to the relevant biotic ligand) Note: these are base-1 indexed.
#' @param CATarget numeric, the target critical accumulation in units of mol /
#'   kg (only used when DoTox == TRUE)
#'
#' @return list with the following elements:
#' \describe{
#'   \item{SpecConc}{numeric vector (NSpec), the concentrations of each species
#'     for which we have formation reactions}
#'   \item{FinalIter}{integer, the number of Newton-Raphson iterations that we
#'     needed to reach convergence}
#'   \item{FinalMaxError}{numeric, the highest final absolute error fraction  
#'     =max(abs(Resid / TotMoles))}
#'   \item{CalcTotConc}{numeric vector (NComp), the calculated total
#'     concentrations of each component in the simulation (units of e.g., mol/L
#'     and mol/kg)}
#' }
#' @export
#'
CHESS <- function(QuietFlag, ConvergenceCriteria, MaxIter, NMass, NComp, NSpec, NBLMetal, SpecMC, SpecK, SpecTempKelvin, SpecDeltaH, SpecStoich, SpecCharge, SpecActCorr, SpecCtoM, SpecName, CompType, CompName, TotConc, DoWHAM, AqueousMC, SolHS, wMolWt, wRadius, wP, wDLF, wKZED, SysTempKelvin, DoTox, MetalName, MetalComp, BLMetalSpecs, CATarget) {
    .Call(`_BLMEngineInR_CHESS`, QuietFlag, ConvergenceCriteria, MaxIter, NMass, NComp, NSpec, NBLMetal, SpecMC, SpecK, SpecTempKelvin, SpecDeltaH, SpecStoich, SpecCharge, SpecActCorr, SpecCtoM, SpecName, CompType, CompName, TotConc, DoWHAM, AqueousMC, SolHS, wMolWt, wRadius, wP, wDLF, wKZED, SysTempKelvin, DoTox, MetalName, MetalComp, BLMetalSpecs, CATarget)
}

